services:

  front: 
    container_name: front
    build:
      context: ../web/
      dockerfile: front.dockerfile
    ports:
      - "8085:80"

  postgres:
    image: postgres:17.2
    container_name: postgres
    volumes:
      - ./.postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_DB=backend
      - POSTGRES_PASSWORD=backendpass
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backend"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/marc-realm.json
    volumes:
      - ./keycloak/import/:/opt/keycloak/data/import/
    command:
      - start-dev
      - --import-realm
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

  

  minio:
    image: "minio/minio:latest"
    container_name: minio
    ports:
      - "9000:9000"
      - "8900:8900"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - minio:/data/minio
    command: minio server /data/minio --console-address ':8900'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 3

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: [ "/bin/sh", "-c", "
      mc alias set myminio http://minio:9000 minio password;
      mc ls myminio/trybucket || mc mb myminio/trybucket;
    " ]


volumes:
  pgadmin_data:
  keycloak_data:
    driver: local
  grafana_data:
    driver: local
  minio:
    driver: local
