spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/backend
    username: backend
    password: backendpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.marc.trapuce.tech/realms/marc
          jwk-set-uri: http://keycloak.marc.trapuce.tech/realms/marc/protocol/openid-connect/certs

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    server:
      url: "http://backend.marc.trapuce.tech/api"
  swagger-ui:
    path: /swagger-ui

server:
  port: 8082
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics
  endpoint:
    prometheus:
      cache.time-to-live: 10s
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true

minio:
  endpoint: http://minio:9000
  access-key: minio
  secret-key: password
  bucket:
    name: trybucket
